### ISSUE TITLE
cuBLAS Error in EAGLE Implementation with LLaMA-3-8B-Instruct on H100 GPU

### ISSUE THREAD

**Issue by zzmmzzm** [thunlp/FR-Spec#3]
First of all, thank you for your excellent work on the FR-Spec project! It's a fantastic contribution to the field of speculative decoding tokenizer.
I'm encountering a cuBLAS error when running the EAGLE implementation with LLaMA-3-8B-Instruct model. The baseline script works perfectly, but the EAGLE script fails consistently. I would greatly appreciate your guidance on this issue.

Environment:

- GPU: H100
- CUDA: 12.1
- cuBLAS: 12.1
- PyTorch cuDNN: 90100
- Model: LLaMA-3-8B-Instruct
- Data type: float16

Error Details:

```
cuBLAS error at /cpfs/user/zhumo/FR-Spec/src/model/linear.cuh:13
```
Steps to Reproduce:

1. Run bash scripts/human_eval/llama3-8b-instruct/run_eagle.sh
2. Error occurs consistently at the same location in linear.cuh:13
Key Observations:

- run_baseline.sh works perfectly without any issues
- run_eagle.sh fails with cuBLAS error
- Error occurs in custom CUDA implementation ( linear.cuh )
- Sufficient GPU memory available (H100 with 80GB)
- All library versions are compatible and properly installed
Attempted Solutions:

- Disabled CUDA Graph
- Tried different data types (float32 shows "Unsupported dtype" error)
- Set various CUDA environment variables
- Verified cuBLAS installation and versions, and I have had set the arch to "90" in setup.py.

**Comment by Achazwl** [comment]
I'll try it later. This code has only been run on A100 and 4090 before.

**Comment by zzmmzzm** [comment]
OK! Thank you for your help and I'm looking forward to hearing good news from you soon!

**Comment by Achazwl** [comment]
I just ran a test and noticed that the `src/cutlass` directory in the Git submodule of the repository was missing. I've re-uploaded it—sorry about that. I also uploaded an examples folder. I followed `examples/example_generate.py` and ran it on the H100, and it works fine. (I only test llama3.2-1b currently, since the network is quite slow)

Could you pull the updates, change the cutlass version to that I uploaded, reinstall the package, and run the example?

**Comment by Achazwl** [comment]
@zzmmzzm I found some possibly relevant bugs and fixed them in the main branch.

**Comment by zzmmzzm** [comment]
Oh, thank you so much for your reply during the holiday! I'll try it at once. I'm sorry for that it didn't work on my gpu for your 3days ago upload. I'll try this one in the afternoon.
